cache:
  paths:
  - node_modules

pages:
  stage: deploy
  image: node:latest
  script:
  # install dependencies & build the code
  - "npm install"
  - "npm run build"
  artifacts:
    paths:
    - public
  only:
    - release