version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - "./__might__:/__might__"
    command: "might --quiet"
  tests-update:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - "./__might__:/__might__"
    command: "might -u --quiet --clean"