[context.production]
  command = "npm run build"

  [context.production.environment]
    NODE_ENV = "production"
    SENTRY_ORG = "herpproject"
    SENTRY_PROJECT = "frontend"
    SENTRY_AUTH_TOKEN = "6c95c196504d49eaa220ca3558f5a5fbdbb4c4ac03c344a4b3dc4f937c7e5d39"

[context.deploy-preview.environment]
  NODE_ENV = "test"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200