[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "16.14.2"
  YARN_VERSION = "1.22.18"

[context.development]
  command = "yarn build:test"

[context.deploy-preview]
  command = "yarn build:test"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200