import React, { useEffect } from 'react';

import ReactMarkdown from 'react-markdown';

import { createStyle } from '../flcss.js';

const input = `
# Privacy Policy

Welcome to Kuruit Bedan Fash5.

[Herp Project](https://herpproject.com) ("us", "we", or "our") operates the https://bedan.me website (hereinafter referred to as the "Service").

The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this Service and compliant to the Company’s terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to Herp Project. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.

One of our main priorities is the privacy of our visitors. This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.

We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://bedan.me/terms/.

### Definitions
  * **Service**
 
  Service is the https://bedan.me website, operated by [Herp Project](https://herpproject.com).
  
  * **Personal Data**

  Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).

  * **Usage Data** 
  
  Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

  * **Cookies**

  Cookies are small files stored on your device (computer or mobile device).

### Information Collection and Use

We collect several different types of information for various purposes to provide and improve our Service to you.

### Types of Data Collected

  * **Personal Data**

  On this particular service (operated form the https://bedan.me) Usage Data is collected anonymously, as in no part of that Usage Data can be traced back to one specific person that we can identify, we'll never ask you to provide us with any kind of personal information.

  * **Usage Data**

  We collect information about how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

  * **Tracking & Cookies Data**

  We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
  
  Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
  
  You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.

  Examples of Cookies we use:

    * **Session Cookies:** We use Session Cookies to operate our Service.  
    * **Preference Cookies:** We use Preference Cookies to remember your preferences and various settings.  
    * **Security Cookies:** We use Security Cookies for security purposes.

### Use of Data

The Company uses the collected data for various purposes:

  * To provide and maintain the Service.
  * To notify you about changes to our Service.
  * To allow you to participate in interactive features of our Service when you choose to do so.
  * To provide customer care and support.
  * To provide analysis or valuable information so that we can improve the Service.
  * To monitor the usage of the Service.
  * To detect, prevent and address technical issues.

### Service Providers

We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.

These third parties have access to your Usage Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.

  **Analytics**

  We may use third-party Service Providers to monitor and analyze the use of our Service.

  * **Google Analytics** Google Analytics is a web analytics service. https://policies.google.com/technologies/partner-sites

**Ads**
  We may use third-party Service Providers to show ads on our Service.

  * **Google Ads** Google Ads is an online advertising platform where advertisers pay to display brief advertisements on services like our Service. https://policies.google.com/technologies/ads

### Children's Privacy

Our Service does not address anyone under the age of 18 ("Children").
  
We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.

### Third Party Privacy Policies

This Service's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.

### Links to Other Sites

Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

### Online Privacy Policy Only

This Privacy Policy applies only to our online activities and is valid for visitors of this Service with regards to the information that they shared and/or collect in this Service. This policy is not applicable to any information collected offline or via channels other than this Service.

### Consent

By using this Service, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.

### Changes to This Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We will let you know via a prominent notice on this Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

### Contact Us

If you have any questions about this Privacy Policy, please contact us:

  * **Email:** contact@herpproject.com
`;

const PrivacyPolicy = () =>
{
  // on url change reset scroll position
  useEffect(() =>
  {
    document.title = 'Privacy Policy';
    
    window.scrollTo(0, 0);
  }, [ window.location ]);

  return <ReactMarkdown className={ styles.container } source={ input }/>;
};

const styles = createStyle({
  container: {
    fontFamily: '"Montserrat", sans-serif',

    fontSize: '14px',
    padding: '5vh 5vw'
  }
});

export default PrivacyPolicy;