name: test

on:
  push:
    branches:
    - development
    - release
    
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '14.x'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: errors
          path: might.error.*.png
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:coverage
      - name: Upload results Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./__coverage__/
          fail_ci_if_error: true
